### ISSUE TITLE
Weikio.NugetDownloader not available

### ISSUE THREAD

**Issue by ApocDev** [weikio/PluginFramework#42]
It looks like you made a change to use this NuGet package in #35, however the package doesn't exist on NuGet yet.

I suggest either reverting the change from #35 or publishing the package so 3rd party development can be done here. :)

**Comment by mikoskinen** [comment]
Hey @ApocDev and thanks for reporting this. And sorry for the problem.

Weikio.NugetDownloader 1.0.0 is now available from [Nuget ](https://www.nuget.org/packages/Weikio.NugetDownloader/). The source for this package is available from https://github.com/weikio/NugetDownloader.

Commit f9489a6 changes the project to reference 1.0.0 of NugetDownloader and should fix the issue. Let me know if you encounter other problems with this.

Regarding Weikio.NugetDownloader, it is just a copy of the code which previously was located in the Nuget catalog. The API surface of the NugetDownloader is not pretty so it is likely that we at some point make it better. But for now, the library is only used by the catalog.
